# Generated by Django 4.0.6 on 2022-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='updated date'),
        ),
    ]
