# Generated by Django 4.0.6 on 2022-11-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_alter_userprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='id')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=False, max_length=8)),
                ('dob', models.DateField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='id')),
                ('created_at', models.DateTimeField(null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated at')),
                ('runtime', models.DecimalField(decimal_places=3, max_digits=7)),
                ('language', models.CharField(blank=True, max_length=500, null=True, verbose_name='language')),
                ('tagline', models.CharField(blank=True, max_length=500, null=True, verbose_name='tagline')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='active'),
        ),
    ]
