# Generated by Django 4.0.6 on 2022-11-16 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='OnetoOneField_Creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='castname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movie.cast'),
            preserve_default=False,
        ),
    ]
