# Generated by Django 4.0.6 on 2022-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_cast_onetoonefield_creator_movie_castname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='name'),
        ),
    ]
